### PR TITLE
Settings: Fixed loading and defaults.

### LINKED ISSUE #93: Cannot open saved worlds from the File - Open World menu on Mac
OS X 10.11.6, Minutor v2.1.0, Minecraft 1.10.2

Worlds are saved in the default location: /Users/<username>/Library/Application Support/minecraft/saves

There are several saved worlds therein.

Starting Minutor and selecting File - Open World from the menu does not show any worlds to open.

It is still possible to select File - Open and manually browse to the world's save directory to open a world, but as the Library folder is hidden this is an extra complication.

### PR DESCRIPTION
**Pull request by madmaxoft**
The "use default location" was not applied when starting Minutor. This change produces more understandable flow of the settings initialization.

Fixes #93, at least on Windows.

### CODE REVIEW

**Comment by EtlamGit** [comment]
Hi @madmaxoft , as it seems that there are some ambiguities what location to choose in the settings dialog, I see these options for us to improve:
* write an extra comment to use the Minecraft base folder not the saves folder
* automatically detect a wrong chosen saves folder and remove it
* work with both variants, as the saves folder may be named differently anyway

While thinking more about it, I prefer the last option. What do you think?

**Comment by madmaxoft** [comment]
I'm always for making things easier for the end user, so working with both would be my choice. However, it is outside of the scope of this PR, I think.

**Comment by madmaxoft** [comment]
@EtlamGit How about this behavior:
- The Settings object always contains the base folder
- When the user browses for the "Minecraft Location", the code in the Browse button handler inspects the folder they choose. If it is named "saves" and has no "saves" subfolder in it, the code uses the parent folder silently.

This should work for all the cases and prevent any confusion. The only case it wouldn't work would be if the user had a world named "saves" and they chose the saves folder instead of the base folder. But I think it's better to leave it like that.

**Comment by EtlamGit** [comment]
(The only save method would be to search for a folder that contains subfolders which themselves contain a file called level.dat that parses to valid NBT data.)

I like your approach...

**Comment by mrkite** [comment]
My only concern is you don't want the program walking all over the place, recursively checking directories for level.dat.  Especially if they point to something really slow like a network drive.  So we definitely want to keep the automatic checking to a minimum.

File: settings.h [hunk 1]
```diff
@@ -15,6 +15,10 @@ class Settings : public QDialog {
   bool verticalDepth;
   QString mcpath;
 
+
+  /** Returns the default path to be used for Minecraft location. */
+  static QString getDefaultLocation();
```
Comment (tigerw) [inline settings.h]: @madmaxoft xoft, is this by any chance, a Cuberite-style comment, in *minutor*?

Comment (tigerw) [reply settings.h]: What is this, some sort of crossover episode?
